name: Build MFC Project

on:
  #防止fork乱用action设置只能手动触发构建
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 MSBuild 环境
      # 这个 Action 会自动寻找并配置 MSBuild 环境
      uses: microsoft/setup-msbuild@v2

    - name: 还原 NuGet 包 (如果项目有使用)
      run: nuget restore iClick.sln

    - name: 编译项目
      shell: cmd
      run: |
        msbuild iClick.sln /p:Configuration=Release /p:Platform=x86 /p:PlatformToolset=v143
        # 如果需要编译 x64 版本，请修改 Platform 为 x64

    - name: 上传打包产物
      uses: actions/upload-artifact@v4
      with:
        name: iClick-Release-Binary
        # 根据你的输出路径调整，通常在 Release 文件夹下
        path: Release/*.exe